344 update naics
RMI-PACTA/r2dii.data pull request #355
Opened 2024-03-18 15:26 UTC by jdhoffa

This PR updates the `NAICS` dataset to the latest version (published in "2022"). 

Relates to #344 

@jacobvjk would appreciate a content review of this (especially on if some of these sectors should be Borderline). Steel in particular I was very unsure of.

2024-03-19 08:09 UTC, jdhoffa commented
For posterity, the original raw data was pulled from here: https://www.census.gov/naics/?48967

2024-03-19 12:31 UTC, jdhoffa commented
@jacobvjk updated the bridge to include all levels. 
This PR is ready for review now

2024-03-19 13:57 UTC, jacobvjk requested changes
A few changes I would suggest mostly relating to borderline inclusion.

In general, I am still unsure about how close to the core business we want a code to be in order to be considered `borderline == TRUE`. Especially in steel production there are a number of products that require high temperature furnaces in their processes. But I am unsure if this means that companies are often integrated

2024-03-19 13:57 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^2111", code) ~ "oil and gas",
```suggestion
    grepl("^211", code) ~ "oil and gas",
    code %in% c("213111", "213112") ~ "oil and gas",
```

2024-03-19 13:57 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^21211", code) ~ "coal",
```suggestion
    grepl("^2121", code) ~ "coal",
    code == "213113" ~ "coal",
```

2024-03-19 13:57 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code == "213113" ~ TRUE,
```suggestion
   grepl("^21311", code) ~ TRUE,
```

2024-03-19 13:57 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^22111", code) ~ "power",
```suggestion
    grepl("^22111", code) ~ "power",
    code == "2211" ~ "power",
```

2024-03-19 13:57 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    TRUE ~ FALSE
```suggestion
    code == "2211" ~ TRUE,
    code %in% c("331512", "331513") ~ TRUE,
    TRUE ~ FALSE
```

2024-03-19 13:57 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code %in% c("4811", "481112") ~ TRUE,
```suggestion
    code %in% c("4811", "48111", "481112") ~ TRUE,
    code %in% c("4812", "48121", "481212", "481219") ~ TRUE,
```

2024-03-19 14:42 UTC, jacobvjk reviewed
updated suggestions for steel based on https://www.transitionmonitor.com/wp-content/uploads/2020/09/steel_ef_final_pacta_banks_v1.2_14-09-2020.pdf and https://ieaghg.org/docs/General_Docs/Reports/PH3-30%20iron-steel.pdf

2024-03-19 15:00 UTC, jacobvjk requested changes
somehow my latest steel suggestions were lost in the process

2024-03-19 15:00 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code %in% c("331110", "331512", "331513") ~ "steel",
```suggestion
    grepl("^3311", code) ~ "steel",
    grepl("^3312", code) ~ "steel",
    code %in% c("331512", "331513") ~ "steel",
```

2024-03-19 15:00 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    TRUE ~ FALSE
this is still open

2024-03-19 15:00 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^3311", code) ~ "steel",
```suggestion
    grepl("^3312", code) ~ "steel",
```

2024-03-19 15:18 UTC, jdhoffa commented
> somehow my latest steel suggestions were lost in the process

ok this turned out very difficult to ensure i did correctly with half being "commit suggestions" and half just being "this is still open". 

Tried to manually update it as you suggested but i may have made a mistake.

2024-03-19 15:34 UTC, jacobvjk commented
> > somehow my latest steel suggestions were lost in the process
> 
> ok this turned out very difficult to ensure i did correctly with half being "commit suggestions" and half just being "this is still open".
> 
> Tried to manually update it as you suggested but i may have made a mistake.

I will give it another full review just to be sure

2024-03-19 16:02 UTC, jacobvjk requested changes
some broader borderline definitions

2024-03-19 16:02 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code == "3361" ~ TRUE,
```suggestion
    code %in% c("336", "3361") ~ TRUE,
```

2024-03-19 16:02 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^33612", code) ~ TRUE,
```suggestion
    grepl("^33612", code) ~ TRUE,
    grepl("^3362", code) ~ TRUE,
    grepl("^3363", code) ~ TRUE,
```

2024-03-20 08:26 UTC, jdhoffa commented on data-raw/classification_bridge.R
> +    code == "2211" ~ "power",
What does this mean?

2024-03-20 08:33 UTC, jdhoffa commented on data-raw/classification_bridge.R
> +    grepl("^3361", code) ~ "automotive",
This seems to not be correct:

![Screenshot 2024-03-20 at 09 33 11](https://github.com/RMI-PACTA/r2dii.data/assets/8741309/88bf0b8d-dd42-4836-b13c-c6801488cad5)

2024-03-20 08:34 UTC, jdhoffa commented on data-raw/classification_bridge.R
> +    grepl("^3361", code) ~ "automotive",
Changed it to:
``` r
    grepl("^3361", code) ~ "automotive",
    grepl("^3362", code) ~ "automotive",
    grepl("^3363", code) ~ "automotive",
```

2024-03-20 08:35 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code == "2211" ~ "power",
"see above". but you addressed this now

2024-03-20 08:36 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^3361", code) ~ "automotive",
woops, definitely a bit too broad

2024-03-20 09:54 UTC, jacobvjk requested changes
Last change. We validated that casting steel in foundries is in-scope and therefore these two codes should not be borderline

2024-03-20 09:54 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code %in% c("331512", "331513") ~ TRUE,
```suggestion
```

2024-03-20 10:00 UTC, jacobvjk approved these changes
lgtm

2024-03-20 10:08 UTC, merged