feat: update to latest version of GICS
RMI-PACTA/r2dii.data pull request #359
Opened 2024-03-19 13:37 UTC by jdhoffa

* `gics_classification` gets update to the 2023 version
* `gics_classification` gains column `version` indicating this

Closes #358

2024-03-19 15:30 UTC, jacobvjk requested changes
some changes, mainly for borderline classifications, but also for steel and power

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
>  gics_classification <- dplyr::select(
the exported data does not seem to be sorted by code. maybe good to add

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^1010204", code) ~ TRUE,
```suggestion
    grepl("^1010204", code) ~ TRUE,
    code == "15104050" ~ TRUE,
```
steel is borderline imo because "Producers of iron and steel and related products, including metallurgical (coking) coal mining used for steel production" contains related products which may be downstream. Also mineral extraction for steel is borderline at best from a steel point of view


<br class="Apple-interchange-newline">

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^2510", code) ~ "automotive",
```suggestion
    grepl("^2510", code) ~ "automotive",
    code == "20106010" ~ "automotive",
```

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    code == "2510" ~ TRUE,
```suggestion
    code == "20106010" ~TRUE,
    code == "2510" ~ TRUE,
```
HDV manufacturing borderline in scope

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^20302", code) ~ "aviation",
```suggestion
    grepl("^20301", code) ~ "aviation",
    grepl("^20302", code) ~ "aviation",
```

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^15102", code) ~ TRUE,
```suggestion
    grepl("^20301", code) ~ TRUE,
    grepl("^15102", code) ~ TRUE,
```
adding aviation freight as borderline

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    grepl("^55", code) ~ "power",
```suggestion
    grepl("^551010", code) ~ "power",
    grepl("^551030", code) ~ "power",
    grepl("^551050", code) ~ "power",
```

2024-03-19 15:30 UTC, jacobvjk commented on data-raw/classification_bridge.R
> +    TRUE ~ FALSE
```suggestion
    grepl("^551030", code) ~ "power",
    grepl("^551050", code) ~ "power",
    TRUE ~ FALSE
```

2024-03-20 08:24 UTC, jdhoffa commented
Changed as requested (and re-sourced and documented).
This should be good to go @jacobvjk

2024-03-20 08:32 UTC, jacobvjk approved these changes
lgtm

2024-03-20 08:49 UTC, merged